### ISSUE TITLE
Vector aggregator chart update fails

### ISSUE THREAD

**Issue by aliusmiles** [timberio/helm-charts#25]
I'm using vector-aggregator chart with helmfile and update fails with:

  > Error: UPGRADE FAILED: cannot patch "vector" with kind StatefulSet: StatefulSet.apps "vector" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

helmfile diff (reducted):
```yaml
monitoring, vector, StatefulSet (apps) has changed:
  # Source: vector-aggregator/templates/statefulset.yaml
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: vector
    labels:
-     helm.sh/chart: vector-aggregator-0.16.1
+     helm.sh/chart: vector-aggregator-0.17.0
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vector
      app.kubernetes.io/version: "0.16.1"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: vector
  spec:
    ...
    volumeClaimTemplates:
      # Vector will store it's data here.
      - metadata:
          name: data-dir
          labels:
-           helm.sh/chart: vector-aggregator-0.16.1
+           helm.sh/chart: vector-aggregator-0.17.0
            app.kubernetes.io/name: vector
            app.kubernetes.io/instance: vector
            app.kubernetes.io/version: "0.16.1"
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/part-of: vector
```

Reason: ` {{- include "libvector.labels" $ | nindent 10 }}` [in sts template](https://github.com/timberio/helm-charts/blob/719424bf23aa15f17d7a9dd0b17009b36133b788/charts/vector-aggregator/templates/statefulset.yaml#L143) which comes from [vector-shared](https://github.com/timberio/helm-charts/blob/719424bf23aa15f17d7a9dd0b17009b36133b788/charts/vector-shared/templates/_labels.tpl#L6)

Looks like the only solution is to remove chart version from volumeClamTempalte's labels, please check [this issue](https://github.com/helm/charts/issues/7803)
